defaults:
  - _self_
  - logger: tensorboard
  - model: resnet
  - metric: f1_score
  - optimizer: adamw
  - criterion: cross_entropy
  - transform: light
  - trainer: torchvision_trainer
  - data: fruits
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  seed: 42
  device: cuda
  n_classes: 131
  n_epochs: 10
  batch_size: 512
  n_workers: 4
  image_width: 224
  image_height: 224
  amp: true
  save_scripted_model: true
  pretrained_weights: null # ${general.artifacts_dir}/${general.run_name}/${general.checkpoint_path}/best.pt # null
  project_dir: ${hydra:runtime.cwd}
  checkpoint_path: weights
  artifacts_dir: ${general.project_dir}/logs/train_artifacts
  run_name: ${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${general.artifacts_dir}/${general.run_name}
  sweep:
    dir: ${general.artifacts_dir}/${general.run_name}
    subdir: ${hydra.job.override_dirname}
